spring.application.name=high-concurrency-ticketing-engine

# 1. Server Port
server.port=8080

# 2. Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://{DB_HOST:localhost}:5432/{DB_NAME:ticket_db}
spring.datasource.username={DB_USER:root}
spring.datasource.password={DB_PASSWORD:password123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 4. RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Kích hoạt cơ chế Retry cho Consumer
spring.rabbitmq.listener.simple.retry.enabled=true
# Thời gian chờ giữa các lần thử lại (3000ms = 3 giây)
spring.rabbitmq.listener.simple.retry.initial-interval=3000ms
# Số lần thử lại tối đa (Bao gồm cả lần chạy đầu tiên)
spring.rabbitmq.listener.simple.retry.max-retries=3
# Hệ số nhân thời gian chờ cho lần sau (Lần 1: 3s, Lần 2: 6s...)
spring.rabbitmq.listener.simple.retry.multiplier=2.0
# Tắt chế độ tự động đẩy lại vào queue cũ khi thất bại toàn tập, để nó chạy sang DLQ
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# JWT Configuration
# Chuỗi bí mật 256-bit (Đã được mã hóa Base64). Tuyệt đối không để lộ chuỗi này trên Production!
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Thời gian sống của token: 86400000 mili-giây = 1 ngày
application.security.jwt.expiration=86400000