spring.application.name=high-concurrency-ticketing-engine

# 1. TỐI ƯU HÓA TOMCAT (WEB SERVER)
# Tăng số luồng phục vụ đồng thời từ 200 lên 1000
server.tomcat.threads.max=1000
# Tăng hàng đợi cho các request phải chờ (khi 1000 luồng trên đã bận)
server.tomcat.accept-count=1500
# Tối đa số lượng kết nối TCP được giữ cùng lúc
server.tomcat.max-connections=10000

# 2. TỐI ƯU HÓA HIKARICP (DATABASE CONNECTION POOL)
# Tăng số lượng kết nối Database từ 10 lên 100 để lưu đơn hàng nhanh hơn
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=20

# 3. Server Port
server.port=8080

# 4. Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://{DB_HOST:localhost}:5432/{DB_NAME:ticket_db}
spring.datasource.username={DB_USER:root}
spring.datasource.password={DB_PASSWORD:password123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 5. Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 6. RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Kích hoạt cơ chế Retry cho Consumer
spring.rabbitmq.listener.simple.retry.enabled=true
# Thời gian chờ giữa các lần thử lại (3000ms = 3 giây)
spring.rabbitmq.listener.simple.retry.initial-interval=3000ms
# Số lần thử lại tối đa (Bao gồm cả lần chạy đầu tiên)
spring.rabbitmq.listener.simple.retry.max-retries=3
# Hệ số nhân thời gian chờ cho lần sau (Lần 1: 3s, Lần 2: 6s...)
spring.rabbitmq.listener.simple.retry.multiplier=2.0
# Tắt chế độ tự động đẩy lại vào queue cũ khi thất bại toàn tập, để nó chạy sang DLQ
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# 7. JWT Configuration
# Chuỗi bí mật 256-bit (Đã được mã hóa Base64). Tuyệt đối không để lộ chuỗi này trên Production!
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Thời gian sống của token: 86400000 mili-giây = 1 ngày
application.security.jwt.expiration=86400000